model_name: sigsigvae
hyperparameters:
  lr: 1e-3
  # lr: 3e-4
  z_dim: 16
  dissimilarity:
    - [ce]
  autoencoding_loss: fixed-variance
  fixed_gamma: [0.001, 0.01, 0.1, 1, 10, 100]
  hidden_channels:
    - [32, 64, 128, 256]
dataset: mnist
logger_path: runs.icml/betas/mnist
batch_size: 128
cuda_sync: false
very_verbose: false
epochs: 100
lr_decay: 1e-1