model_name: sigsigvae
hyperparameters:
  lr: 1e-3
  # lr: 3e-4
  z_dim: 64
  dissimilarity:
    - [sse]
  autoencoding_loss: fixed-variance
  fixed_gamma: [0.001, 0.01, 0.1, 1, 10, 100]
dataset: svhn
logger_path: runs/betas/svhn
batch_size: 128
cuda_sync: false
very_verbose: false
epochs: 100
lr_decay: 1e-1