model_name: sigsigvae
hyperparameters:
  lr: 1e-3
  # lr: 3e-4
  z_dim: 64
  dissimilarity:
    - [mse]
  autoencoding_loss: log
  hidden_channels:
    - [32, 64, 128, 256]
dataset: cifar10
logger_path: runs/gammas3/cifar10
batch_size: 128
cuda_sync: false
very_verbose: false
epochs: 100
lr_decay: 1e-1