model_name: dfcvae
hyperparameters:
  lr: 1e-3
  z_dim: 64
  beta: 1
dataset: food101
logger_path: runs.icml/cms/food101
batch_size: 128
cuda_sync: false
very_verbose: false
epochs: 100
lr_decay: 1e-1