model_name: sintrovae
hyperparameters:
  lr: 2e-4
  z_dim: 64
  beta_rec: 1
  beta_kl: 1
  beta_neg: 256
  gamma_r: 1e-8
dataset: celeba
logger_path: runs.icml/cms/celeba
batch_size: 128
cuda_sync: false
very_verbose: false
epochs: 100
# lr_decay: 1e-1