model_name: twostagevae
hyperparameters:
  # lr: 1e-3
  lr: 3e-4
  z_dim: 16
dataset: mnist
logger_path: runs/cms/mnist
batch_size: 128
cuda_sync: false
very_verbose: false
epochs: 100
# lr_decay: 1e-1