model_name: sigsigvae
hyperparameters:
  lr: 1e-3
  z_dim: 64
  dissimilarity:
    - [mse]
    - [mae]
    - [ce]
    - [ssim]
    - [cossim]
    - [iwssim]
    - [vif]
    - [fsim]
    - [srsim]
    - [gmsd]
    - [vsi]
    - [dss]
    - [content-score]
    - [style-score]
    - [haarpsi]
    - [mdsi]
    - [lpips]
    - [pieapp]
    - [dists]
    - [mse, lpips]
    - [mae, lpips]
dataset: food101
logger_path: runs/main/food101
batch_size: 128
cuda_sync: false
very_verbose: false
epochs: 100
lr_decay: 1e-1